openapi: 3.0.2
info:
  title: Items_MS API
  version: 1.0.0
  description: List of items API
  contact:
    name: Maarika Lukk
    url: 'https://github.com/maarikal'
    email: maarika.lukk@voco.ee
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
paths:
  /items:
    summary: Path used to manage the list of items.
    description: >-
      The REST endpoint/path used to list and create zero or more `items` entities.  This path contains
      a `GET` and `POST` operation to perform the list and create tasks, respectively.
    get:
      tags:
        - Items
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Item returned:
                  value:
                    Item: Item returned
          description: Returns items
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Bad Request:
                  value:
                    error: Bad Request
          description: Bad Request
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Conflict:
                  value:
                    error: Item already exists
          description: Conflict
      security:
        - Bearer: [ ]
      summary: Get all items
      description: Gets a list of all `items` entities.
    post:
      requestBody:
        description: A new `items` to be created.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
          text/xml:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      tags:
        - Items
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Item returned:
                  value:
                    Item: Item returned
            text/xml:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Item returned:
                  value: "<text>Item returned</text>\r\n"
          description: Return item
      security:
        - Bearer: [ ]
      operationId: createitems
      summary: Create a item
      description: Creates a new instance of a `items`.
  /users:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          text/xml:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      tags:
        - Users
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                User returned:
                  value:
                    User: Returned
            text/xml:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                User returned:
                  value: <text>User returned</text>
          description: Return user
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Bad Request:
                  value:
                    error: Bad Request
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                '"Bad Request':
                  value: <text>"Bad Request</text>
          description: Bad request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                'Password ':
                  value:
                    error: Password is required
                Password lengths:
                  value:
                    error: Password must be at least 8 characters long
                Email:
                  value:
                    error: Email is required
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Password is required:
                  value: <text>Password is required</text>
                Password must be at least 8 characters long:
                  value: <text>Password must be at least 8 characters long</text>
                Email is required":
                  value: <text>Email is required"</text>
          description: Invalid email or password
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                User exists:
                  value:
                    error: User already exists
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                User already exists:
                  value: <text>User already exists</text>
          description: User already exists
      security:
        - Bearer: [ ]
      summary: Create a new user
  /users/check-email:
    post:
      tags:
        - Users
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Email is valid:
                  value:
                    User: Email is valid
          description: Email is valid
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                User is created:
                  value:
                    User: Created
          description: User is created
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Bad Request:
                  value:
                    error: Bad Request
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Email is required:
                  value:
                    error: Email is required
                Password must be at least 8 characters long:
                  value:
                    error: Password must be at least 8 characters long
                Invalid email structure:
                  value:
                    error: Invalid email structure
          description: |-
            Email and password is required.
            Password must be at least 8 characters long
        '409':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Email already exists:
                  value:
                    error: Email already exists
          description: Email already exists
      security:
        - Bearer: [ ]
      summary: Create a new email
  /health-check:
    get:
      tags:
        - Health-checks
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Is Working:
                  value:
                    error: works
          description: OK
      summary: Get project load information
  /sessions:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          text/xml:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      tags:
        - Sessions
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
              examples:
                SessionId:
                  value:
                    Session: SessionId created
            text/xml:
              schema:
                $ref: '#/components/schemas/Session'
              examples:
                SessionId:
                  value: <text>SessionId created</text>
          description: Send sessionId
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Bad Request Error:
                  value:
                    error: Bad Request Error
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Bad Request Error:
                  value: <text>Bad Request Error</text>
          description: Bad Request
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Authorization missing:
                  value:
                    error: Authorization header is missing
                Bearer:
                  value:
                    error: Authorization header is not in Bearer XXX format
                Session not found:
                  value:
                    error: Session not found
                User not found:
                  value:
                    error: User not found
                Unauthorized:
                  value:
                    error: Unauthorized
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Authorization missing:
                  value: <text>Authorization header is missing</text>
                Bearer:
                  value: <text>Authorization header is not in Bearer XXX format</text>
                Session not found:
                  value: <text>Session not found</text>
                User not found:
                  value: <text>User not found</text>
                Unauthorized:
                  value: <text>Unauthorized</text>
          description: Unauthorized
      security:
        - Bearer: [ ]
      summary: Create a new session
    delete:
      tags:
        - Sessions
      responses:
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Session'
              examples:
                SessionId deleted:
                  value:
                    Session: SessionId deleted
          description: SessionId deleted
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Unauthorized:
                  value:
                    error: Unauthorized
                Session not found:
                  value:
                    error: Session not found
                "Authorization missing\t":
                  value:
                    error: Authorization header is missing
                Bearer:
                  value:
                    error: Authorization header is not in Bearer XXX
                User not found:
                  value:
                    error: User not found
          description: Unauthorized
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                No session:
                  value:
                    error: No session found
          description: No session found
      security:
        - Bearer: [ ]
      summary: Delete a session
  '/items?id={itemsId}':
    summary: Path used to manage a single items.
    description: >-
      The REST endpoint/path used to get, update, and delete single instances of an `items`.  This path
      contains `GET`, `PUT`, and `DELETE` operations used to perform the get, update, and delete tasks,
      respectively.
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
          text/xml:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      tags:
        - Items
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Item:
                  value:
                    Item: Item returned
            text/xml:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Item returned:
                  value: <text>Item returned</text>
          description: Return item
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Item created:
                  value:
                    Item: Item created
            text/xml:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Item created:
                  value: <text>Item created</text>
          description: Item created
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Response:
                  value:
                    Item: Successful response
            text/xml:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Successful response:
                  value: <text>Successful response</text>
          description: Successful response.
      security:
        - Bearer: [ ]
      operationId: updateitem
      summary: Update a item
      description: Updates an existing item.
    post:
      requestBody:
        description: Added item information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
          text/xml:
            schema:
              $ref: '#/components/schemas/Item'
        required: true
      tags:
        - Items
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Created:
                  value:
                    Item: Item has created
            text/xml:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Created:
                  value: <text>Item created</text>
          description: Item created
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                ' Successful response.':
                  value:
                    Item: Successful response
            text/xml:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                ' Successful response.':
                  value: <text>Successful response</text>
          description: Successful response.
      security:
        - Bearer: [ ]
      operationId: addeditem
      summary: Add a new item
      description: Added new item.
    delete:
      tags:
        - Items
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                Item deleted:
                  value:
                    Item: Deleted
          description: Return item
        '204':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
              examples:
                Successful response.:
                  value:
                    Item: Successful response
          description: Successful response.
      security:
        - Bearer: [ ]
      operationId: deleteitems
      summary: Delete a item
      description: Deletes an existing `items`.
    parameters:
      - name: itemsId
        description: A unique identifier for a `items`.
        schema:
          type: string
        in: path
        required: true
components:
  schemas:
    User:
      title: Root Type for User
      description: 'If person have signed up, then he will be on database. With these data he/she can sign in too.'
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: test@test.ee
        id: 1
        password: qwerty12
    Item:
      title: Root Type for items
      description: Items list
      type: object
      properties:
        description:
          type: string
        image:
          type: string
        name:
          type: string
      example:
        item: item nr 1
        description: it is green and small
        image: >-
          https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhBY9h14uKCSgCxNCZEhClbX2ksq2Fi6iCmQ&usqp=CAU
    Session:
      title: Root Type for Session
      description: 'If user is on webpage and have logged in, then he/she has a sessionId.'
      type: object
      properties:
        user:
          type: string
        password:
          type: string
      example:
        user: test@test.ee
        password: qwerty123
    Credentials:
      title: Root Type for Credentials
      description: ''
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: test@test.ee
        password: qwerty123
    Error:
      description: |-
        {
            "error:" "Error message"
        }
      type: object
  securitySchemes:
    Bearer:
      scheme: bearer
      type: http
tags:
  - name: Items
    description: ''
  - name: Sessions
    description: ''
  - name: Users
    description: ''
  - name: Health-checks
    description: ''
